CREATE TABLE IF NOT EXISTS t_user (id integer GENERATED BY DEFAULT AS IDENTITY, stu_id integer NOT NULL, stu_name varchar(255) NOT NULL, score integer NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, PRIMARY KEY (id))
ALTER TABLE t_user ADD CONSTRAINT uk_stu_id UNIQUE (stu_id)
